# Generated by Django 4.1.7 on 2023-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='coi',
            field=models.FileField(default='media.png', max_length=200, upload_to='files'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='ci@cyanase.com', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moa',
            field=models.FileField(default='media.png', max_length=200, upload_to='files'),
        ),
        migrations.AddField(
            model_name='user',
            name='super',
            field=models.BooleanField(default=False),
        ),
    ]
